### ISSUE TITLE
q) prompt improvements

### ISSUE THREAD

**Issue by abalkin** [enlnt/Q.jl#52]
# TODO

1. [ ] Account for window size in q output.
2. [ ] Detect incomplete input and allow entering multi-line commands.
    - Start with simply detecting unbalanced parentheses.
3. [ ] Suppress output from commands ending in `;`.
